// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: api/booking-service-proto/booking.proto

package bookingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestStatus int32

const (
	RequestStatus_REQUEST_STATUS_UNSPECIFIED RequestStatus = 0
	RequestStatus_REQUEST_STATUS_PENDING     RequestStatus = 1
	RequestStatus_REQUEST_STATUS_ACCEPTED    RequestStatus = 2
	RequestStatus_REQUEST_STATUS_IN_PROGRESS RequestStatus = 3
	RequestStatus_REQUEST_STATUS_COMPLETED   RequestStatus = 4
)

// Enum value maps for RequestStatus.
var (
	RequestStatus_name = map[int32]string{
		0: "REQUEST_STATUS_UNSPECIFIED",
		1: "REQUEST_STATUS_PENDING",
		2: "REQUEST_STATUS_ACCEPTED",
		3: "REQUEST_STATUS_IN_PROGRESS",
		4: "REQUEST_STATUS_COMPLETED",
	}
	RequestStatus_value = map[string]int32{
		"REQUEST_STATUS_UNSPECIFIED": 0,
		"REQUEST_STATUS_PENDING":     1,
		"REQUEST_STATUS_ACCEPTED":    2,
		"REQUEST_STATUS_IN_PROGRESS": 3,
		"REQUEST_STATUS_COMPLETED":   4,
	}
)

func (x RequestStatus) Enum() *RequestStatus {
	p := new(RequestStatus)
	*p = x
	return p
}

func (x RequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_booking_service_proto_booking_proto_enumTypes[0].Descriptor()
}

func (RequestStatus) Type() protoreflect.EnumType {
	return &file_api_booking_service_proto_booking_proto_enumTypes[0]
}

func (x RequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestStatus.Descriptor instead.
func (RequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_booking_service_proto_booking_proto_rawDescGZIP(), []int{0}
}

type BookingStatus int32

const (
	BookingStatus_BOOKING_STATUS_UNSPECIFIED BookingStatus = 0
	BookingStatus_BOOKING_STATUS_SCHEDULED   BookingStatus = 1
	BookingStatus_BOOKING_STATUS_IN_PROGRESS BookingStatus = 2
	BookingStatus_BOOKING_STATUS_COMPLETED   BookingStatus = 3
)

// Enum value maps for BookingStatus.
var (
	BookingStatus_name = map[int32]string{
		0: "BOOKING_STATUS_UNSPECIFIED",
		1: "BOOKING_STATUS_SCHEDULED",
		2: "BOOKING_STATUS_IN_PROGRESS",
		3: "BOOKING_STATUS_COMPLETED",
	}
	BookingStatus_value = map[string]int32{
		"BOOKING_STATUS_UNSPECIFIED": 0,
		"BOOKING_STATUS_SCHEDULED":   1,
		"BOOKING_STATUS_IN_PROGRESS": 2,
		"BOOKING_STATUS_COMPLETED":   3,
	}
)

func (x BookingStatus) Enum() *BookingStatus {
	p := new(BookingStatus)
	*p = x
	return p
}

func (x BookingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_booking_service_proto_booking_proto_enumTypes[1].Descriptor()
}

func (BookingStatus) Type() protoreflect.EnumType {
	return &file_api_booking_service_proto_booking_proto_enumTypes[1]
}

func (x BookingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookingStatus.Descriptor instead.
func (BookingStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_booking_service_proto_booking_proto_rawDescGZIP(), []int{1}
}

type CreateRequestRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CustomerProfileId int64                  `protobuf:"varint,1,opt,name=customer_profile_id,json=customerProfileId,proto3" json:"customer_profile_id,omitempty"`
	CategoryId        int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateRequestRequest) Reset() {
	*x = CreateRequestRequest{}
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestRequest) ProtoMessage() {}

func (x *CreateRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_service_proto_booking_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequestRequest) GetCustomerProfileId() int64 {
	if x != nil {
		return x.CustomerProfileId
	}
	return 0
}

func (x *CreateRequestRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateRequestRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequestResponse) Reset() {
	*x = CreateRequestResponse{}
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestResponse) ProtoMessage() {}

func (x *CreateRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_service_proto_booking_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListCustomerRequestsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CustomerProfileId int64                  `protobuf:"varint,1,opt,name=customer_profile_id,json=customerProfileId,proto3" json:"customer_profile_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListCustomerRequestsRequest) Reset() {
	*x = ListCustomerRequestsRequest{}
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomerRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomerRequestsRequest) ProtoMessage() {}

func (x *ListCustomerRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomerRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListCustomerRequestsRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_service_proto_booking_proto_rawDescGZIP(), []int{2}
}

func (x *ListCustomerRequestsRequest) GetCustomerProfileId() int64 {
	if x != nil {
		return x.CustomerProfileId
	}
	return 0
}

type ListCustomerRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*ServiceRequest      `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomerRequestsResponse) Reset() {
	*x = ListCustomerRequestsResponse{}
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomerRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomerRequestsResponse) ProtoMessage() {}

func (x *ListCustomerRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomerRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListCustomerRequestsResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_service_proto_booking_proto_rawDescGZIP(), []int{3}
}

func (x *ListCustomerRequestsResponse) GetRequests() []*ServiceRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type ServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,3,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        RequestStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=booking.v1.RequestStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRequest) Reset() {
	*x = ServiceRequest{}
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequest) ProtoMessage() {}

func (x *ServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequest.ProtoReflect.Descriptor instead.
func (*ServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_service_proto_booking_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ServiceRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ServiceRequest) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ServiceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceRequest) GetStatus() RequestStatus {
	if x != nil {
		return x.Status
	}
	return RequestStatus_REQUEST_STATUS_UNSPECIFIED
}

func (x *ServiceRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateBookingRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WorkerProfileId   int64                  `protobuf:"varint,2,opt,name=worker_profile_id,json=workerProfileId,proto3" json:"worker_profile_id,omitempty"`
	CustomerProfileId int64                  `protobuf:"varint,3,opt,name=customer_profile_id,json=customerProfileId,proto3" json:"customer_profile_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_service_proto_booking_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBookingRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *CreateBookingRequest) GetWorkerProfileId() int64 {
	if x != nil {
		return x.WorkerProfileId
	}
	return 0
}

func (x *CreateBookingRequest) GetCustomerProfileId() int64 {
	if x != nil {
		return x.CustomerProfileId
	}
	return 0
}

type CreateBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingResponse) Reset() {
	*x = CreateBookingResponse{}
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingResponse) ProtoMessage() {}

func (x *CreateBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingResponse.ProtoReflect.Descriptor instead.
func (*CreateBookingResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_service_proto_booking_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListCustomerBookingsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CustomerProfileId int64                  `protobuf:"varint,1,opt,name=customer_profile_id,json=customerProfileId,proto3" json:"customer_profile_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListCustomerBookingsRequest) Reset() {
	*x = ListCustomerBookingsRequest{}
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomerBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomerBookingsRequest) ProtoMessage() {}

func (x *ListCustomerBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomerBookingsRequest.ProtoReflect.Descriptor instead.
func (*ListCustomerBookingsRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_service_proto_booking_proto_rawDescGZIP(), []int{7}
}

func (x *ListCustomerBookingsRequest) GetCustomerProfileId() int64 {
	if x != nil {
		return x.CustomerProfileId
	}
	return 0
}

type ListWorkerBookingsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerProfileId int64                  `protobuf:"varint,1,opt,name=worker_profile_id,json=workerProfileId,proto3" json:"worker_profile_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListWorkerBookingsRequest) Reset() {
	*x = ListWorkerBookingsRequest{}
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkerBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkerBookingsRequest) ProtoMessage() {}

func (x *ListWorkerBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkerBookingsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkerBookingsRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_service_proto_booking_proto_rawDescGZIP(), []int{8}
}

func (x *ListWorkerBookingsRequest) GetWorkerProfileId() int64 {
	if x != nil {
		return x.WorkerProfileId
	}
	return 0
}

type ListBookingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*Booking             `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingsResponse) Reset() {
	*x = ListBookingsResponse{}
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingsResponse) ProtoMessage() {}

func (x *ListBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingsResponse.ProtoReflect.Descriptor instead.
func (*ListBookingsResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_service_proto_booking_proto_rawDescGZIP(), []int{9}
}

func (x *ListBookingsResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

type Booking struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BookingId          int64                  `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	RequestId          int64                  `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WorkerProfileId    int64                  `protobuf:"varint,3,opt,name=worker_profile_id,json=workerProfileId,proto3" json:"worker_profile_id,omitempty"`
	CustomerProfileId  int64                  `protobuf:"varint,4,opt,name=customer_profile_id,json=customerProfileId,proto3" json:"customer_profile_id,omitempty"`
	CategoryId         int64                  `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName       string                 `protobuf:"bytes,6,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	RequestDescription string                 `protobuf:"bytes,7,opt,name=request_description,json=requestDescription,proto3" json:"request_description,omitempty"`
	Status             BookingStatus          `protobuf:"varint,8,opt,name=status,proto3,enum=booking.v1.BookingStatus" json:"status,omitempty"`
	ScheduledTime      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	StartTime          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime            *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	FinalPrice         *string                `protobuf:"bytes,12,opt,name=final_price,json=finalPrice,proto3,oneof" json:"final_price,omitempty"`
	CounterpartyName   string                 `protobuf:"bytes,13,opt,name=counterparty_name,json=counterpartyName,proto3" json:"counterparty_name,omitempty"`
	CounterpartyRole   string                 `protobuf:"bytes,14,opt,name=counterparty_role,json=counterpartyRole,proto3" json:"counterparty_role,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_api_booking_service_proto_booking_proto_rawDescGZIP(), []int{10}
}

func (x *Booking) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *Booking) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Booking) GetWorkerProfileId() int64 {
	if x != nil {
		return x.WorkerProfileId
	}
	return 0
}

func (x *Booking) GetCustomerProfileId() int64 {
	if x != nil {
		return x.CustomerProfileId
	}
	return 0
}

func (x *Booking) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Booking) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *Booking) GetRequestDescription() string {
	if x != nil {
		return x.RequestDescription
	}
	return ""
}

func (x *Booking) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

func (x *Booking) GetScheduledTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledTime
	}
	return nil
}

func (x *Booking) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Booking) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Booking) GetFinalPrice() string {
	if x != nil && x.FinalPrice != nil {
		return *x.FinalPrice
	}
	return ""
}

func (x *Booking) GetCounterpartyName() string {
	if x != nil {
		return x.CounterpartyName
	}
	return ""
}

func (x *Booking) GetCounterpartyRole() string {
	if x != nil {
		return x.CounterpartyRole
	}
	return ""
}

type UpdateBookingStatusRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BookingId       int64                  `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	WorkerProfileId int64                  `protobuf:"varint,2,opt,name=worker_profile_id,json=workerProfileId,proto3" json:"worker_profile_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateBookingStatusRequest) Reset() {
	*x = UpdateBookingStatusRequest{}
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingStatusRequest) ProtoMessage() {}

func (x *UpdateBookingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookingStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_booking_service_proto_booking_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateBookingStatusRequest) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *UpdateBookingStatusRequest) GetWorkerProfileId() int64 {
	if x != nil {
		return x.WorkerProfileId
	}
	return 0
}

type UpdateBookingStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingStatusResponse) Reset() {
	*x = UpdateBookingStatusResponse{}
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingStatusResponse) ProtoMessage() {}

func (x *UpdateBookingStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_booking_service_proto_booking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateBookingStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_booking_service_proto_booking_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateBookingStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_booking_service_proto_booking_proto protoreflect.FileDescriptor

const file_api_booking_service_proto_booking_proto_rawDesc = "" +
	"\n" +
	"'api/booking-service-proto/booking.proto\x12\n" +
	"booking.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x01\n" +
	"\x14CreateRequestRequest\x12.\n" +
	"\x13customer_profile_id\x18\x01 \x01(\x03R\x11customerProfileId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"1\n" +
	"\x15CreateRequestResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"M\n" +
	"\x1bListCustomerRequestsRequest\x12.\n" +
	"\x13customer_profile_id\x18\x01 \x01(\x03R\x11customerProfileId\"V\n" +
	"\x1cListCustomerRequestsResponse\x126\n" +
	"\brequests\x18\x01 \x03(\v2\x1a.booking.v1.ServiceRequestR\brequests\"\x85\x02\n" +
	"\x0eServiceRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x03 \x01(\tR\fcategoryName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x121\n" +
	"\x06status\x18\x05 \x01(\x0e2\x19.booking.v1.RequestStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x91\x01\n" +
	"\x14CreateBookingRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\x12*\n" +
	"\x11worker_profile_id\x18\x02 \x01(\x03R\x0fworkerProfileId\x12.\n" +
	"\x13customer_profile_id\x18\x03 \x01(\x03R\x11customerProfileId\"1\n" +
	"\x15CreateBookingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"M\n" +
	"\x1bListCustomerBookingsRequest\x12.\n" +
	"\x13customer_profile_id\x18\x01 \x01(\x03R\x11customerProfileId\"G\n" +
	"\x19ListWorkerBookingsRequest\x12*\n" +
	"\x11worker_profile_id\x18\x01 \x01(\x03R\x0fworkerProfileId\"G\n" +
	"\x14ListBookingsResponse\x12/\n" +
	"\bbookings\x18\x01 \x03(\v2\x13.booking.v1.BookingR\bbookings\"\x92\x05\n" +
	"\aBooking\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\x03R\tbookingId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x03R\trequestId\x12*\n" +
	"\x11worker_profile_id\x18\x03 \x01(\x03R\x0fworkerProfileId\x12.\n" +
	"\x13customer_profile_id\x18\x04 \x01(\x03R\x11customerProfileId\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x03R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x06 \x01(\tR\fcategoryName\x12/\n" +
	"\x13request_description\x18\a \x01(\tR\x12requestDescription\x121\n" +
	"\x06status\x18\b \x01(\x0e2\x19.booking.v1.BookingStatusR\x06status\x12A\n" +
	"\x0escheduled_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rscheduledTime\x129\n" +
	"\n" +
	"start_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12$\n" +
	"\vfinal_price\x18\f \x01(\tH\x00R\n" +
	"finalPrice\x88\x01\x01\x12+\n" +
	"\x11counterparty_name\x18\r \x01(\tR\x10counterpartyName\x12+\n" +
	"\x11counterparty_role\x18\x0e \x01(\tR\x10counterpartyRoleB\x0e\n" +
	"\f_final_price\"g\n" +
	"\x1aUpdateBookingStatusRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\x03R\tbookingId\x12*\n" +
	"\x11worker_profile_id\x18\x02 \x01(\x03R\x0fworkerProfileId\"7\n" +
	"\x1bUpdateBookingStatusResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*\xa6\x01\n" +
	"\rRequestStatus\x12\x1e\n" +
	"\x1aREQUEST_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16REQUEST_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17REQUEST_STATUS_ACCEPTED\x10\x02\x12\x1e\n" +
	"\x1aREQUEST_STATUS_IN_PROGRESS\x10\x03\x12\x1c\n" +
	"\x18REQUEST_STATUS_COMPLETED\x10\x04*\x8b\x01\n" +
	"\rBookingStatus\x12\x1e\n" +
	"\x1aBOOKING_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18BOOKING_STATUS_SCHEDULED\x10\x01\x12\x1e\n" +
	"\x1aBOOKING_STATUS_IN_PROGRESS\x10\x02\x12\x1c\n" +
	"\x18BOOKING_STATUS_COMPLETED\x10\x032\xae\x05\n" +
	"\x0eBookingService\x12T\n" +
	"\rCreateRequest\x12 .booking.v1.CreateRequestRequest\x1a!.booking.v1.CreateRequestResponse\x12i\n" +
	"\x14ListCustomerRequests\x12'.booking.v1.ListCustomerRequestsRequest\x1a(.booking.v1.ListCustomerRequestsResponse\x12T\n" +
	"\rCreateBooking\x12 .booking.v1.CreateBookingRequest\x1a!.booking.v1.CreateBookingResponse\x12a\n" +
	"\x14ListCustomerBookings\x12'.booking.v1.ListCustomerBookingsRequest\x1a .booking.v1.ListBookingsResponse\x12]\n" +
	"\x12ListWorkerBookings\x12%.booking.v1.ListWorkerBookingsRequest\x1a .booking.v1.ListBookingsResponse\x12_\n" +
	"\fStartBooking\x12&.booking.v1.UpdateBookingStatusRequest\x1a'.booking.v1.UpdateBookingStatusResponse\x12b\n" +
	"\x0fCompleteBooking\x12&.booking.v1.UpdateBookingStatusRequest\x1a'.booking.v1.UpdateBookingStatusResponseB-Z+diploma/api/booking-service-proto;bookingpbb\x06proto3"

var (
	file_api_booking_service_proto_booking_proto_rawDescOnce sync.Once
	file_api_booking_service_proto_booking_proto_rawDescData []byte
)

func file_api_booking_service_proto_booking_proto_rawDescGZIP() []byte {
	file_api_booking_service_proto_booking_proto_rawDescOnce.Do(func() {
		file_api_booking_service_proto_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_booking_service_proto_booking_proto_rawDesc), len(file_api_booking_service_proto_booking_proto_rawDesc)))
	})
	return file_api_booking_service_proto_booking_proto_rawDescData
}

var file_api_booking_service_proto_booking_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_booking_service_proto_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_booking_service_proto_booking_proto_goTypes = []any{
	(RequestStatus)(0),                   // 0: booking.v1.RequestStatus
	(BookingStatus)(0),                   // 1: booking.v1.BookingStatus
	(*CreateRequestRequest)(nil),         // 2: booking.v1.CreateRequestRequest
	(*CreateRequestResponse)(nil),        // 3: booking.v1.CreateRequestResponse
	(*ListCustomerRequestsRequest)(nil),  // 4: booking.v1.ListCustomerRequestsRequest
	(*ListCustomerRequestsResponse)(nil), // 5: booking.v1.ListCustomerRequestsResponse
	(*ServiceRequest)(nil),               // 6: booking.v1.ServiceRequest
	(*CreateBookingRequest)(nil),         // 7: booking.v1.CreateBookingRequest
	(*CreateBookingResponse)(nil),        // 8: booking.v1.CreateBookingResponse
	(*ListCustomerBookingsRequest)(nil),  // 9: booking.v1.ListCustomerBookingsRequest
	(*ListWorkerBookingsRequest)(nil),    // 10: booking.v1.ListWorkerBookingsRequest
	(*ListBookingsResponse)(nil),         // 11: booking.v1.ListBookingsResponse
	(*Booking)(nil),                      // 12: booking.v1.Booking
	(*UpdateBookingStatusRequest)(nil),   // 13: booking.v1.UpdateBookingStatusRequest
	(*UpdateBookingStatusResponse)(nil),  // 14: booking.v1.UpdateBookingStatusResponse
	(*timestamppb.Timestamp)(nil),        // 15: google.protobuf.Timestamp
}
var file_api_booking_service_proto_booking_proto_depIdxs = []int32{
	6,  // 0: booking.v1.ListCustomerRequestsResponse.requests:type_name -> booking.v1.ServiceRequest
	0,  // 1: booking.v1.ServiceRequest.status:type_name -> booking.v1.RequestStatus
	15, // 2: booking.v1.ServiceRequest.created_at:type_name -> google.protobuf.Timestamp
	12, // 3: booking.v1.ListBookingsResponse.bookings:type_name -> booking.v1.Booking
	1,  // 4: booking.v1.Booking.status:type_name -> booking.v1.BookingStatus
	15, // 5: booking.v1.Booking.scheduled_time:type_name -> google.protobuf.Timestamp
	15, // 6: booking.v1.Booking.start_time:type_name -> google.protobuf.Timestamp
	15, // 7: booking.v1.Booking.end_time:type_name -> google.protobuf.Timestamp
	2,  // 8: booking.v1.BookingService.CreateRequest:input_type -> booking.v1.CreateRequestRequest
	4,  // 9: booking.v1.BookingService.ListCustomerRequests:input_type -> booking.v1.ListCustomerRequestsRequest
	7,  // 10: booking.v1.BookingService.CreateBooking:input_type -> booking.v1.CreateBookingRequest
	9,  // 11: booking.v1.BookingService.ListCustomerBookings:input_type -> booking.v1.ListCustomerBookingsRequest
	10, // 12: booking.v1.BookingService.ListWorkerBookings:input_type -> booking.v1.ListWorkerBookingsRequest
	13, // 13: booking.v1.BookingService.StartBooking:input_type -> booking.v1.UpdateBookingStatusRequest
	13, // 14: booking.v1.BookingService.CompleteBooking:input_type -> booking.v1.UpdateBookingStatusRequest
	3,  // 15: booking.v1.BookingService.CreateRequest:output_type -> booking.v1.CreateRequestResponse
	5,  // 16: booking.v1.BookingService.ListCustomerRequests:output_type -> booking.v1.ListCustomerRequestsResponse
	8,  // 17: booking.v1.BookingService.CreateBooking:output_type -> booking.v1.CreateBookingResponse
	11, // 18: booking.v1.BookingService.ListCustomerBookings:output_type -> booking.v1.ListBookingsResponse
	11, // 19: booking.v1.BookingService.ListWorkerBookings:output_type -> booking.v1.ListBookingsResponse
	14, // 20: booking.v1.BookingService.StartBooking:output_type -> booking.v1.UpdateBookingStatusResponse
	14, // 21: booking.v1.BookingService.CompleteBooking:output_type -> booking.v1.UpdateBookingStatusResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_booking_service_proto_booking_proto_init() }
func file_api_booking_service_proto_booking_proto_init() {
	if File_api_booking_service_proto_booking_proto != nil {
		return
	}
	file_api_booking_service_proto_booking_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_booking_service_proto_booking_proto_rawDesc), len(file_api_booking_service_proto_booking_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_booking_service_proto_booking_proto_goTypes,
		DependencyIndexes: file_api_booking_service_proto_booking_proto_depIdxs,
		EnumInfos:         file_api_booking_service_proto_booking_proto_enumTypes,
		MessageInfos:      file_api_booking_service_proto_booking_proto_msgTypes,
	}.Build()
	File_api_booking_service_proto_booking_proto = out.File
	file_api_booking_service_proto_booking_proto_goTypes = nil
	file_api_booking_service_proto_booking_proto_depIdxs = nil
}
