// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: api/payment-service-proto/payment.proto

package paymentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_COMPLETED   PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 4
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_COMPLETED",
		3: "PAYMENT_STATUS_FAILED",
		4: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_COMPLETED":   2,
		"PAYMENT_STATUS_FAILED":      3,
		"PAYMENT_STATUS_REFUNDED":    4,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_payment_service_proto_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_api_payment_service_proto_payment_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_payment_service_proto_payment_proto_rawDescGZIP(), []int{0}
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     int64                  `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Provider      string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_api_payment_service_proto_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_service_proto_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_service_proto_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *CreatePaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_api_payment_service_proto_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_service_proto_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_service_proto_payment_proto_rawDescGZIP(), []int{1}
}

func (x *GetPaymentRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

type UpdatePaymentStatusRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PaymentId            int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	TransactionReference string                 `protobuf:"bytes,2,opt,name=transaction_reference,json=transactionReference,proto3" json:"transaction_reference,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdatePaymentStatusRequest) Reset() {
	*x = UpdatePaymentStatusRequest{}
	mi := &file_api_payment_service_proto_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentStatusRequest) ProtoMessage() {}

func (x *UpdatePaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_service_proto_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_service_proto_payment_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePaymentStatusRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *UpdatePaymentStatusRequest) GetTransactionReference() string {
	if x != nil {
		return x.TransactionReference
	}
	return ""
}

type PaymentResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PaymentId            int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	BookingId            int64                  `protobuf:"varint,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Amount               float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status               PaymentStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=payment.v1.PaymentStatus" json:"status,omitempty"`
	Provider             string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	TransactionReference string                 `protobuf:"bytes,7,opt,name=transaction_reference,json=transactionReference,proto3" json:"transaction_reference,omitempty"`
	PaymentUrl           string                 `protobuf:"bytes,8,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_api_payment_service_proto_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_service_proto_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_api_payment_service_proto_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentResponse) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *PaymentResponse) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *PaymentResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *PaymentResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PaymentResponse) GetTransactionReference() string {
	if x != nil {
		return x.TransactionReference
	}
	return ""
}

func (x *PaymentResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

var File_api_payment_service_proto_payment_proto protoreflect.FileDescriptor

const file_api_payment_service_proto_payment_proto_rawDesc = "" +
	"\n" +
	"'api/payment-service-proto/payment.proto\x12\n" +
	"payment.v1\"\x85\x01\n" +
	"\x14CreatePaymentRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\x03R\tbookingId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\"2\n" +
	"\x11GetPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\"p\n" +
	"\x1aUpdatePaymentStatusRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\x123\n" +
	"\x15transaction_reference\x18\x02 \x01(\tR\x14transactionReference\"\xa8\x02\n" +
	"\x0fPaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\x03R\tbookingId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x121\n" +
	"\x06status\x18\x05 \x01(\x0e2\x19.payment.v1.PaymentStatusR\x06status\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x123\n" +
	"\x15transaction_reference\x18\a \x01(\tR\x14transactionReference\x12\x1f\n" +
	"\vpayment_url\x18\b \x01(\tR\n" +
	"paymentUrl*\xa1\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18PAYMENT_STATUS_COMPLETED\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x042\xe1\x02\n" +
	"\x0ePaymentService\x12N\n" +
	"\rCreatePayment\x12 .payment.v1.CreatePaymentRequest\x1a\x1b.payment.v1.PaymentResponse\x12H\n" +
	"\n" +
	"GetPayment\x12\x1d.payment.v1.GetPaymentRequest\x1a\x1b.payment.v1.PaymentResponse\x12[\n" +
	"\x14MarkPaymentCompleted\x12&.payment.v1.UpdatePaymentStatusRequest\x1a\x1b.payment.v1.PaymentResponse\x12X\n" +
	"\x11MarkPaymentFailed\x12&.payment.v1.UpdatePaymentStatusRequest\x1a\x1b.payment.v1.PaymentResponseB-Z+diploma/api/payment-service-proto;paymentpbb\x06proto3"

var (
	file_api_payment_service_proto_payment_proto_rawDescOnce sync.Once
	file_api_payment_service_proto_payment_proto_rawDescData []byte
)

func file_api_payment_service_proto_payment_proto_rawDescGZIP() []byte {
	file_api_payment_service_proto_payment_proto_rawDescOnce.Do(func() {
		file_api_payment_service_proto_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_payment_service_proto_payment_proto_rawDesc), len(file_api_payment_service_proto_payment_proto_rawDesc)))
	})
	return file_api_payment_service_proto_payment_proto_rawDescData
}

var file_api_payment_service_proto_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_payment_service_proto_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_payment_service_proto_payment_proto_goTypes = []any{
	(PaymentStatus)(0),                 // 0: payment.v1.PaymentStatus
	(*CreatePaymentRequest)(nil),       // 1: payment.v1.CreatePaymentRequest
	(*GetPaymentRequest)(nil),          // 2: payment.v1.GetPaymentRequest
	(*UpdatePaymentStatusRequest)(nil), // 3: payment.v1.UpdatePaymentStatusRequest
	(*PaymentResponse)(nil),            // 4: payment.v1.PaymentResponse
}
var file_api_payment_service_proto_payment_proto_depIdxs = []int32{
	0, // 0: payment.v1.PaymentResponse.status:type_name -> payment.v1.PaymentStatus
	1, // 1: payment.v1.PaymentService.CreatePayment:input_type -> payment.v1.CreatePaymentRequest
	2, // 2: payment.v1.PaymentService.GetPayment:input_type -> payment.v1.GetPaymentRequest
	3, // 3: payment.v1.PaymentService.MarkPaymentCompleted:input_type -> payment.v1.UpdatePaymentStatusRequest
	3, // 4: payment.v1.PaymentService.MarkPaymentFailed:input_type -> payment.v1.UpdatePaymentStatusRequest
	4, // 5: payment.v1.PaymentService.CreatePayment:output_type -> payment.v1.PaymentResponse
	4, // 6: payment.v1.PaymentService.GetPayment:output_type -> payment.v1.PaymentResponse
	4, // 7: payment.v1.PaymentService.MarkPaymentCompleted:output_type -> payment.v1.PaymentResponse
	4, // 8: payment.v1.PaymentService.MarkPaymentFailed:output_type -> payment.v1.PaymentResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_payment_service_proto_payment_proto_init() }
func file_api_payment_service_proto_payment_proto_init() {
	if File_api_payment_service_proto_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_payment_service_proto_payment_proto_rawDesc), len(file_api_payment_service_proto_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_payment_service_proto_payment_proto_goTypes,
		DependencyIndexes: file_api_payment_service_proto_payment_proto_depIdxs,
		EnumInfos:         file_api_payment_service_proto_payment_proto_enumTypes,
		MessageInfos:      file_api_payment_service_proto_payment_proto_msgTypes,
	}.Build()
	File_api_payment_service_proto_payment_proto = out.File
	file_api_payment_service_proto_payment_proto_goTypes = nil
	file_api_payment_service_proto_payment_proto_depIdxs = nil
}
