// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0--rc1
// source: api/usermanagement-service-proto/usermanagement.proto

package usermanagementpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserManagementService_GetCustomerProfile_FullMethodName = "/usermanagement.v1.UserManagementService/GetCustomerProfile"
	UserManagementService_GetWorkerProfile_FullMethodName   = "/usermanagement.v1.UserManagementService/GetWorkerProfile"
	UserManagementService_HasPaymentMethod_FullMethodName   = "/usermanagement.v1.UserManagementService/HasPaymentMethod"
)

// UserManagementServiceClient is the client API for UserManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserManagementServiceClient interface {
	GetCustomerProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*CustomerProfileResponse, error)
	GetWorkerProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*WorkerProfileResponse, error)
	HasPaymentMethod(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*HasPaymentMethodResponse, error)
}

type userManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserManagementServiceClient(cc grpc.ClientConnInterface) UserManagementServiceClient {
	return &userManagementServiceClient{cc}
}

func (c *userManagementServiceClient) GetCustomerProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*CustomerProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomerProfileResponse)
	err := c.cc.Invoke(ctx, UserManagementService_GetCustomerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementServiceClient) GetWorkerProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*WorkerProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerProfileResponse)
	err := c.cc.Invoke(ctx, UserManagementService_GetWorkerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementServiceClient) HasPaymentMethod(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*HasPaymentMethodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasPaymentMethodResponse)
	err := c.cc.Invoke(ctx, UserManagementService_HasPaymentMethod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserManagementServiceServer is the server API for UserManagementService service.
// All implementations must embed UnimplementedUserManagementServiceServer
// for forward compatibility.
type UserManagementServiceServer interface {
	GetCustomerProfile(context.Context, *GetProfileRequest) (*CustomerProfileResponse, error)
	GetWorkerProfile(context.Context, *GetProfileRequest) (*WorkerProfileResponse, error)
	HasPaymentMethod(context.Context, *GetProfileRequest) (*HasPaymentMethodResponse, error)
	mustEmbedUnimplementedUserManagementServiceServer()
}

// UnimplementedUserManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserManagementServiceServer struct{}

func (UnimplementedUserManagementServiceServer) GetCustomerProfile(context.Context, *GetProfileRequest) (*CustomerProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCustomerProfile not implemented")
}
func (UnimplementedUserManagementServiceServer) GetWorkerProfile(context.Context, *GetProfileRequest) (*WorkerProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkerProfile not implemented")
}
func (UnimplementedUserManagementServiceServer) HasPaymentMethod(context.Context, *GetProfileRequest) (*HasPaymentMethodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasPaymentMethod not implemented")
}
func (UnimplementedUserManagementServiceServer) mustEmbedUnimplementedUserManagementServiceServer() {}
func (UnimplementedUserManagementServiceServer) testEmbeddedByValue()                               {}

// UnsafeUserManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserManagementServiceServer will
// result in compilation errors.
type UnsafeUserManagementServiceServer interface {
	mustEmbedUnimplementedUserManagementServiceServer()
}

func RegisterUserManagementServiceServer(s grpc.ServiceRegistrar, srv UserManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedUserManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserManagementService_ServiceDesc, srv)
}

func _UserManagementService_GetCustomerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementServiceServer).GetCustomerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserManagementService_GetCustomerProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementServiceServer).GetCustomerProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementService_GetWorkerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementServiceServer).GetWorkerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserManagementService_GetWorkerProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementServiceServer).GetWorkerProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementService_HasPaymentMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementServiceServer).HasPaymentMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserManagementService_HasPaymentMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementServiceServer).HasPaymentMethod(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserManagementService_ServiceDesc is the grpc.ServiceDesc for UserManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usermanagement.v1.UserManagementService",
	HandlerType: (*UserManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCustomerProfile",
			Handler:    _UserManagementService_GetCustomerProfile_Handler,
		},
		{
			MethodName: "GetWorkerProfile",
			Handler:    _UserManagementService_GetWorkerProfile_Handler,
		},
		{
			MethodName: "HasPaymentMethod",
			Handler:    _UserManagementService_HasPaymentMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/usermanagement-service-proto/usermanagement.proto",
}
