// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: api/usermanagement-service-proto/usermanagement.proto

package usermanagementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_api_usermanagement_service_proto_usermanagement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_usermanagement_service_proto_usermanagement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_usermanagement_service_proto_usermanagement_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CustomerProfileResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CustomerProfileId int64                  `protobuf:"varint,1,opt,name=customer_profile_id,json=customerProfileId,proto3" json:"customer_profile_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CustomerProfileResponse) Reset() {
	*x = CustomerProfileResponse{}
	mi := &file_api_usermanagement_service_proto_usermanagement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerProfileResponse) ProtoMessage() {}

func (x *CustomerProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_usermanagement_service_proto_usermanagement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerProfileResponse.ProtoReflect.Descriptor instead.
func (*CustomerProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_usermanagement_service_proto_usermanagement_proto_rawDescGZIP(), []int{1}
}

func (x *CustomerProfileResponse) GetCustomerProfileId() int64 {
	if x != nil {
		return x.CustomerProfileId
	}
	return 0
}

type WorkerProfileResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerProfileId int64                  `protobuf:"varint,1,opt,name=worker_profile_id,json=workerProfileId,proto3" json:"worker_profile_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkerProfileResponse) Reset() {
	*x = WorkerProfileResponse{}
	mi := &file_api_usermanagement_service_proto_usermanagement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerProfileResponse) ProtoMessage() {}

func (x *WorkerProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_usermanagement_service_proto_usermanagement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerProfileResponse.ProtoReflect.Descriptor instead.
func (*WorkerProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_usermanagement_service_proto_usermanagement_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerProfileResponse) GetWorkerProfileId() int64 {
	if x != nil {
		return x.WorkerProfileId
	}
	return 0
}

var File_api_usermanagement_service_proto_usermanagement_proto protoreflect.FileDescriptor

const file_api_usermanagement_service_proto_usermanagement_proto_rawDesc = "" +
	"\n" +
	"5api/usermanagement-service-proto/usermanagement.proto\x12\x11usermanagement.v1\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"I\n" +
	"\x17CustomerProfileResponse\x12.\n" +
	"\x13customer_profile_id\x18\x01 \x01(\x03R\x11customerProfileId\"C\n" +
	"\x15WorkerProfileResponse\x12*\n" +
	"\x11worker_profile_id\x18\x01 \x01(\x03R\x0fworkerProfileId2\xe3\x01\n" +
	"\x15UserManagementService\x12f\n" +
	"\x12GetCustomerProfile\x12$.usermanagement.v1.GetProfileRequest\x1a*.usermanagement.v1.CustomerProfileResponse\x12b\n" +
	"\x10GetWorkerProfile\x12$.usermanagement.v1.GetProfileRequest\x1a(.usermanagement.v1.WorkerProfileResponseB;Z9diploma/api/usermanagement-service-proto;usermanagementpbb\x06proto3"

var (
	file_api_usermanagement_service_proto_usermanagement_proto_rawDescOnce sync.Once
	file_api_usermanagement_service_proto_usermanagement_proto_rawDescData []byte
)

func file_api_usermanagement_service_proto_usermanagement_proto_rawDescGZIP() []byte {
	file_api_usermanagement_service_proto_usermanagement_proto_rawDescOnce.Do(func() {
		file_api_usermanagement_service_proto_usermanagement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_usermanagement_service_proto_usermanagement_proto_rawDesc), len(file_api_usermanagement_service_proto_usermanagement_proto_rawDesc)))
	})
	return file_api_usermanagement_service_proto_usermanagement_proto_rawDescData
}

var file_api_usermanagement_service_proto_usermanagement_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_usermanagement_service_proto_usermanagement_proto_goTypes = []any{
	(*GetProfileRequest)(nil),       // 0: usermanagement.v1.GetProfileRequest
	(*CustomerProfileResponse)(nil), // 1: usermanagement.v1.CustomerProfileResponse
	(*WorkerProfileResponse)(nil),   // 2: usermanagement.v1.WorkerProfileResponse
}
var file_api_usermanagement_service_proto_usermanagement_proto_depIdxs = []int32{
	0, // 0: usermanagement.v1.UserManagementService.GetCustomerProfile:input_type -> usermanagement.v1.GetProfileRequest
	0, // 1: usermanagement.v1.UserManagementService.GetWorkerProfile:input_type -> usermanagement.v1.GetProfileRequest
	1, // 2: usermanagement.v1.UserManagementService.GetCustomerProfile:output_type -> usermanagement.v1.CustomerProfileResponse
	2, // 3: usermanagement.v1.UserManagementService.GetWorkerProfile:output_type -> usermanagement.v1.WorkerProfileResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_usermanagement_service_proto_usermanagement_proto_init() }
func file_api_usermanagement_service_proto_usermanagement_proto_init() {
	if File_api_usermanagement_service_proto_usermanagement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_usermanagement_service_proto_usermanagement_proto_rawDesc), len(file_api_usermanagement_service_proto_usermanagement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_usermanagement_service_proto_usermanagement_proto_goTypes,
		DependencyIndexes: file_api_usermanagement_service_proto_usermanagement_proto_depIdxs,
		MessageInfos:      file_api_usermanagement_service_proto_usermanagement_proto_msgTypes,
	}.Build()
	File_api_usermanagement_service_proto_usermanagement_proto = out.File
	file_api_usermanagement_service_proto_usermanagement_proto_goTypes = nil
	file_api_usermanagement_service_proto_usermanagement_proto_depIdxs = nil
}
