// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: api/geolocation-service-proto/geolocation.proto

package geolocationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindNearbyWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	RadiusMeters  int64                  `protobuf:"varint,4,opt,name=radius_meters,json=radiusMeters,proto3" json:"radius_meters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNearbyWorkersRequest) Reset() {
	*x = FindNearbyWorkersRequest{}
	mi := &file_api_geolocation_service_proto_geolocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNearbyWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNearbyWorkersRequest) ProtoMessage() {}

func (x *FindNearbyWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_geolocation_service_proto_geolocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNearbyWorkersRequest.ProtoReflect.Descriptor instead.
func (*FindNearbyWorkersRequest) Descriptor() ([]byte, []int) {
	return file_api_geolocation_service_proto_geolocation_proto_rawDescGZIP(), []int{0}
}

func (x *FindNearbyWorkersRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *FindNearbyWorkersRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *FindNearbyWorkersRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *FindNearbyWorkersRequest) GetRadiusMeters() int64 {
	if x != nil {
		return x.RadiusMeters
	}
	return 0
}

type FindNearbyWorkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*NearbyWorker        `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNearbyWorkersResponse) Reset() {
	*x = FindNearbyWorkersResponse{}
	mi := &file_api_geolocation_service_proto_geolocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNearbyWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNearbyWorkersResponse) ProtoMessage() {}

func (x *FindNearbyWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_geolocation_service_proto_geolocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNearbyWorkersResponse.ProtoReflect.Descriptor instead.
func (*FindNearbyWorkersResponse) Descriptor() ([]byte, []int) {
	return file_api_geolocation_service_proto_geolocation_proto_rawDescGZIP(), []int{1}
}

func (x *FindNearbyWorkersResponse) GetWorkers() []*NearbyWorker {
	if x != nil {
		return x.Workers
	}
	return nil
}

type NearbyWorker struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerId        int64                  `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	FullName        string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Price           int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	ExperienceLevel string                 `protobuf:"bytes,4,opt,name=experience_level,json=experienceLevel,proto3" json:"experience_level,omitempty"`
	CategoryName    string                 `protobuf:"bytes,5,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Latitude        float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude       float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	DistanceMeters  float64                `protobuf:"fixed64,8,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NearbyWorker) Reset() {
	*x = NearbyWorker{}
	mi := &file_api_geolocation_service_proto_geolocation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyWorker) ProtoMessage() {}

func (x *NearbyWorker) ProtoReflect() protoreflect.Message {
	mi := &file_api_geolocation_service_proto_geolocation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyWorker.ProtoReflect.Descriptor instead.
func (*NearbyWorker) Descriptor() ([]byte, []int) {
	return file_api_geolocation_service_proto_geolocation_proto_rawDescGZIP(), []int{2}
}

func (x *NearbyWorker) GetWorkerId() int64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *NearbyWorker) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *NearbyWorker) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *NearbyWorker) GetExperienceLevel() string {
	if x != nil {
		return x.ExperienceLevel
	}
	return ""
}

func (x *NearbyWorker) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *NearbyWorker) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *NearbyWorker) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *NearbyWorker) GetDistanceMeters() float64 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

var File_api_geolocation_service_proto_geolocation_proto protoreflect.FileDescriptor

const file_api_geolocation_service_proto_geolocation_proto_rawDesc = "" +
	"\n" +
	"/api/geolocation-service-proto/geolocation.proto\x12\x0egeolocation.v1\"\x9a\x01\n" +
	"\x18FindNearbyWorkersRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12#\n" +
	"\rradius_meters\x18\x04 \x01(\x03R\fradiusMeters\"S\n" +
	"\x19FindNearbyWorkersResponse\x126\n" +
	"\aworkers\x18\x01 \x03(\v2\x1c.geolocation.v1.NearbyWorkerR\aworkers\"\x91\x02\n" +
	"\fNearbyWorker\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\x03R\bworkerId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12)\n" +
	"\x10experience_level\x18\x04 \x01(\tR\x0fexperienceLevel\x12#\n" +
	"\rcategory_name\x18\x05 \x01(\tR\fcategoryName\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12'\n" +
	"\x0fdistance_meters\x18\b \x01(\x01R\x0edistanceMeters2~\n" +
	"\x12GeolocationService\x12h\n" +
	"\x11FindNearbyWorkers\x12(.geolocation.v1.FindNearbyWorkersRequest\x1a).geolocation.v1.FindNearbyWorkersResponseB5Z3diploma/api/geolocation-service-proto;geolocationpbb\x06proto3"

var (
	file_api_geolocation_service_proto_geolocation_proto_rawDescOnce sync.Once
	file_api_geolocation_service_proto_geolocation_proto_rawDescData []byte
)

func file_api_geolocation_service_proto_geolocation_proto_rawDescGZIP() []byte {
	file_api_geolocation_service_proto_geolocation_proto_rawDescOnce.Do(func() {
		file_api_geolocation_service_proto_geolocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_geolocation_service_proto_geolocation_proto_rawDesc), len(file_api_geolocation_service_proto_geolocation_proto_rawDesc)))
	})
	return file_api_geolocation_service_proto_geolocation_proto_rawDescData
}

var file_api_geolocation_service_proto_geolocation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_geolocation_service_proto_geolocation_proto_goTypes = []any{
	(*FindNearbyWorkersRequest)(nil),  // 0: geolocation.v1.FindNearbyWorkersRequest
	(*FindNearbyWorkersResponse)(nil), // 1: geolocation.v1.FindNearbyWorkersResponse
	(*NearbyWorker)(nil),              // 2: geolocation.v1.NearbyWorker
}
var file_api_geolocation_service_proto_geolocation_proto_depIdxs = []int32{
	2, // 0: geolocation.v1.FindNearbyWorkersResponse.workers:type_name -> geolocation.v1.NearbyWorker
	0, // 1: geolocation.v1.GeolocationService.FindNearbyWorkers:input_type -> geolocation.v1.FindNearbyWorkersRequest
	1, // 2: geolocation.v1.GeolocationService.FindNearbyWorkers:output_type -> geolocation.v1.FindNearbyWorkersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_geolocation_service_proto_geolocation_proto_init() }
func file_api_geolocation_service_proto_geolocation_proto_init() {
	if File_api_geolocation_service_proto_geolocation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_geolocation_service_proto_geolocation_proto_rawDesc), len(file_api_geolocation_service_proto_geolocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_geolocation_service_proto_geolocation_proto_goTypes,
		DependencyIndexes: file_api_geolocation_service_proto_geolocation_proto_depIdxs,
		MessageInfos:      file_api_geolocation_service_proto_geolocation_proto_msgTypes,
	}.Build()
	File_api_geolocation_service_proto_geolocation_proto = out.File
	file_api_geolocation_service_proto_geolocation_proto_goTypes = nil
	file_api_geolocation_service_proto_geolocation_proto_depIdxs = nil
}
